---
title: "CAV Energy and Demand - Compact Aggregate Equations"

date: "Dec. 15, 2018"

author:
  - name: Paul N. Leiby
    email: leibypn@ornl.gov
    affiliation: Oak Ridge National Laboratory

address:
  - code: Oak Ridge National Laboratory
    address: ORNL Energy Analysis Group, One Bethel Valley Road, Oak Ridge, TN, 37831-6036
  
abstract:  A compact and aggregated model of road vehicle travel and energy use for Connected and Automated Vehicles

output: 
  word_document:
    toc: true
    fig_caption: yes
    fig_height: 5
    fig_width: 7
    df_print: kable
    reference_docx: mystyles.docx
#   pdf_document: default

file: CAV_compact_agg_equations.Rmd
---

```{r global_options, include=FALSE}
library(knitr)
#opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
```
# 1. Objective

We describe *CAVESIM*, a techno-economic model for Connected and Automated Vehicle Energy SIMulation. CAVESIM combines a technology-based decomposition of the energy use and travel 
demand effects of vehicle automation with a utility-maximizing framework for travel demand and vehicle energy intensity that responds to the financial and time-costs of travel.

# 2. Decomposition of Energy and GHG Impacts of CAVs

The composition of the effects of many mechanisms by which CAVs influence energy use and emissions can be conveniently accounted with a _Kaya Identity_

In this *Kaya* or *ASIF* approach the total GHG emissions are the product of

1. the level of **A**ctivity (e.g., passenger miles of travel), 
2. the **S**hare of activity for each mode, vehicle, and fuel type, 
3. the energy **I**ntensity of the mode and vehicle type (e.g., energy use per vehicle mile), and 
4. the **F**uel carbon intensity (ghg emission mass per unit energy)

Energy use for particular vehicle type is given by total activity (travel demand) level $A_{tv}$, 
the share of travel on mode *m* and the average share-weighted energy intensity of travel by vehicle type and mode.

$$E_{tvf} = (A_{tv}/o_{tv}) ~ \sigma_{tmv} ~I({\vec x}_{tmv}) \phi_{tmvf}$$
Vehicle energy intensity *I* is a function of a vector $\vec x_{tmv}$ of CAV mechanism/technology levels.

Transportation GHG emissions are then the sum over all transportation modes, vehicle types, and fuels of the product of {Transportation Services Activity^[We differentiate between transportation services (PKT) and vehicle travel (VKT).]} x {Shares of each mode-vehicle-fuel type} x {Energy Intensity} x {Fuel GHG Intensity}.

$$G_t = \Sigma_{m,v} (A_{tv}/o_{tv}) ~ \sigma_{tmv} ~I(\vec x_{tmv}) ~\Sigma_f g_{tf} \phi_{tmvf}$$

Defining indices

- m = transportation mode
- v = vehicle type
- f = fuel type
- t = time period (year)

for sets[^2]

- M = set of transportation modes *m*
- V = set of vehicle types *v*
- F = set of fuel types *f*
- T = set of time periods *t*

[^2]: Additional potential disaggregations include by region, vehicle size class, drivetrain type, and time of day (e.g. operating costs vary by time of day, as described in Bösch et al. 2017).

The variables are

- $A_{tv}$ = the transportation services Activity provided by type (passenger v.s freight, or LDV/HDV) [billion passenger-km or tonne-km traveled/yr]
- $o_{tv}$ = occupancy of each vehicle type v in year t [pass/veh, or PKT/VKT, for passenger travel; tonne/veh for freight]
- $\sigma_{tmv}$ = share of energy services in transportation mode m by vehicle type v in year t [unitless]
- $\phi_{tmvf}$ = the share of energy-service share $\sigma_{tmv}$ produced by fuel type f [unitless]
- $I_{tvmf}$ = the energy intensity of vehicle v in mode m using fuel type f in year t [MJ/veh-km] ([EJ/Bill veh-km])
- $g_{tf}$ = the GHG intensity of fuel f in year t [g CO2e/MJ (MegaT CO2e/EJ)]
- $E_{tvf}$ = energy use in form of fuel f by vehicle type v in year t [EJ/y]
- $G_{tv}$ = GHGs emitted in year t by type v [MT CO2e/y]

Focusing on passenger travel, we can write energy use $E_{tvf}$ as

$$E_{tvf} = A_{tv} \cdot \frac {1}{o_{tv}} \cdot \Sigma_{m} \sigma_{tvm} \phi_{tvmf} I_{tvmf}$$
with units

$$[EJ/yr] = [bill~ pkm/yr] \cdot [vkm/pkm] \cdot [unitlessShare] \cdot [unitlessShare] \cdot [MJ/vkm]$$

Total Emissions are

$$G_{tv} = \Sigma_f E_{tvf} g_{tf}$$

Combining, overall total emissions per year are

$$G_{t} = \Sigma_v \Sigma_f \left [ 
A_{tv} \cdot \frac {1}{o_{tv}} \cdot \Sigma_{m} \left ( \sigma_{tvm} \phi_{tvmf} I_{tvmf} \right ) \right ] g_{tf}$$

Mechanisms by Which CAVs Can Alter Energy Use and Emissions
---------------------------
We identified a set *K* of "Mechanisms" or "Technologies" associated with vehicle automation, each $k \in K$ of which has an effect represented by multiplier $\mu_k$ that can increase or decrease a component term in the ASIF decomposition. In general, a mechanism can affect travel activity levels *A*, vehicle energy intensities *I*, or mode and fuel shares $\sigma, \phi$. 
Furthermore, a mechanism could also effect vehicle class shares or occupancy, but we do not yet consider such effects. 

Taking a Scenario Approach, we can construct scenarios *s* that combine technology cases $j \in J$ and demand cases $d \in D$. For each scenario values are indexed by year *t* (for selected years), vehicle class *v*, mechanism *k* and by the Combined Technology/Demand scenario *s*, i.e. $\mu_{tvks}$???.

# 3. Estimating Energy Impacts

We define the effects of automation on vehicle energy intensity (energy per vehicle km traveled) through a set of identified technological and operational "mechanisms." 

The estimation for the midcase energy intensity impacts of each mechanism is based on literature review^[We start from the values developed in Wadud, MacKenzie and Leiby 2016.] and the external calculations of the authors. Ranges of values, for sensitivity cases and scenarios, are constructed for each mechanism *k*, for effect sensitivity cases *s* from "zero" through "pessimistic," "midcase," and "optimistic." Mechanism intensity effect values $I_{E,tvks}$ indicate the fractional change in energy intensity for a particular mechanism *k*, and are differentiated by year *t*, vehicle class *v*, and effect sensitivity *s*.

### 3.1 Construct multiplicative factors to apply to energy intensities for each mechanism

From the fractional changes in energy intensity, multipliers $\mu_{tvks}$ are constructed to apply for each mechanism/technology *k*, year *t*, vehicle class *v*, and effect sensitivity case *s*.

$\mu_{tvks} = 1.0 + I_{E,tvks}$

A multiplier value of 1.0 indicates no change and less/greater than one implies a multiplicative reduction/increase in energy intensity.

### 3.2 Energy Intensity by Vehicle Type and Technology Scenario, by Composing Mechanism Effects

We construct Scenario Multipliers $\mu_{jtv}$ (supressing subscripts *m, f*) for the vehicle energy intensity of each Scenario *j*, for Year *t* and Vehicle class *v*. These scenario multipliers reflect the combined the effect of all the mechanisms on vehicle energy intensity.

For each technology scenario *j*, year *t*, vehicle class *v*, the estimated "EffectCase" or effect sensitivity case *s* is specified for each mechanism *k*, i.e. 

$s_{jtvk}$ for 
$s \in \{Zero, Low, Mid, High\}$.

This Effect Sensitivity case *s* determines the appropriate intensity multiplier for each mechanism in the technology scenario.

The total energy intensity multiplier for each technology scenario *j* is the product of all mechanism multipliers^[Here mode *m* and fuel *f* are initially fixed and suppressed, i.e. *m* = road_vehicle and *f* = petroleum.] 
$\mu_{jtv} = \prod_{k} \mu_{tvk{s_{jtvk}}}$

$s_{jtvk}$ is the sensitivity case value for mechanism *k* on vehicle class *v* in technology scenario *j* and year *t*.

The Net Energy Intensity change for the technology scenario *j* is the difference between the combined effect of the intensity mechanism multipliers and 1.0.

$$\Delta I_{jtv} \equiv \mu_{jtv}-1 ~=~ \prod_{k} \mu_{tvk{s_{jtvk}}}-1$$

# 4. Demand Response to CAVs

In addition to the changes in energy intensity we account for a travel demand response based on the net change in generalized cost of travel. The change in generalized costs reflects both the change in energy cost per mile and potential changes in several other cost components, including travel time cost and other vehicle capital and operating cost.

4.1 Key parameters for Demand scenarios
-----------------------

4.2 Establish Base Travel Costs for Each Cost Component
---------------------------------

### Simple Base Travel Time Cost Calculation

Unit travel time cost per mile $\underline c_{T,v}$ is differentiated by vehicle class, and depends on average speed and hourly time cost.

4.3 Cost Changes and Fractional Increase in VKT for Demand Scenarios
---------------------------------

Calculate fractional change in demand, by Demand Scenario *d*, Year *t*, and VehicleClass *v*, based on changes in 
time cost, other vehicle fuel and operating costs, and VMT demand elasticity w.r.t generalized cost.

### CAV Scenario Vehicle Travel Cost Shares by Component

Costs are adjusted relative to Base for the cost-related assumptions of each Demand Scenario and for the Energy Intensity change associated with the current Technology Scenario. Energy intensity drives the travel energy cost, but this component is typically less than 15% of total travel costs for LDVs, and less than 35% of total costs for HDVs.

Base cost component shares $\sigma_{ivt}^B$ are normalized and add to 1.0. Demand Scenario *relative* costs for each cost component *i* are relative to the Base (Manual Vehicle) level. The total relative cost for all components can be greater than or less than 1.0. Denoted $\sigma_{ivtdj}$, the scenario travel cost component shares depend on cost component *i*, Vehicle class *v*, Year *t* and Demand Scenario *d*, and TechScenario *j*.

Base fuel costs per mile $\sigma_{fuel,vt}^B$ are adjusted by the Scenario Multipliers for energy intensity, $\mu_{jtv}$ for TechScenario *j*, Year *t*, Vehicle class *v*. The perceived change in fuel cost effects for consumers/riders also depends on the fraction $f_{fuelvis,v})$ of fuel costs that are assumed visible to or perceived by them. That is, for cost component $i = fuel$:

$$\sigma_{fuel,vtdj} = \sigma_{fuel,vt}^B \cdot (1+\mu_{jtv} \cdot f_{fuelvis,v})$$

Other travel cost components *i* have similar scenario-based adjustments, some directly specified by assumption $\gamma_{dtv}$ for demand scenario *d*, year *t* and vehicle class *v*:

$$\sigma_{ivtdj} = \sigma_{ivt}^B \cdot (1+\gamma_{dtv})$$
Note that adjusted travel cost components are all determined relative to the reference level. Thus the adjusted component "shares" are not technically shares, and can total greater or less than 1.0, if the total adjusted costs are greater or less than total base costs.
Their sum indicates the relative travel cost for the combined demand-technology scenario *dj*:

$$c_{rel,vtdj} ~=~ \frac {\sum_i \sigma_{ivtdj}} { \sum_i \sigma_{ivt}^B } ~=~ {\sum_i \sigma_{ivtdj}} $$


4.4 Calculate Adjusted Travel Cost Components for Scenario Conditions
---------------------------

4.5 Fractional VMT Changes in CAV Scenario
-------------------

Compute fractional increases in VKT from the changes in total generalized travel costs that result from automation.

For Vehicle Type *v*, Time *t*, Demand Scenario *d*, Technology Scenario *j*, and Elasticity Case *c* (Low and High elasticity)
[??? is elasticity case to be governed by demand scenario *d*, or separate index *c*?]

Define

- $c_{rel,vtdj}$ = Relative Total Cost for vehicle travel [unitless, vehicle travel cost $/veh-km]
- $m_{vtdj}(c_{rel,vtdj})$ = fractional increase in VKT [unitless, VKT is in km/vehicle-yr]

$$c_{rel,vtdj} \equiv \frac {C_{tot,vtdj}} {C_{tot,vt}^B}$$
The fractional increase in VKT

$$m_{vtdj}(c_{rel,vtdj}) ~=~ (c_{rel,vtdj} )^{ElasVKT_{dv}}-1$$

### Effects on VMT Demand from Underserved Population, and Ride Hailing & Pooling
The fractional change in VMT demand due to the cost-elastic response is augmented by adjustments reflecting:

- estimated additional road travel by underserved/non-driving populations, specifically older and young people;
- a shift from ride hailing/pooling.

Specify Combined Scenarios. A combined scenario $CS_i$ associates each Demand Scenario $DS_i$ with and Underserved Multiplier Option `USOption` and possible further VMT adjustment for ride hailing/pooling (`baseRideHailingPoolingAdj`). Note that all of these demand adjustments, for cost-response $m_{vtdj}(c_{rel,vtdj})$, underserved-demand multiplier \gamma_{USD}, and ride hailing/pooling demand shift $\rho_{HailPool}$, are applied multiplicatively to the base demand level:

$$c_{rel,vtdj} ~=~ RelTotalCost_{vtdj}$$

$$\begin {align} m_{vtdj}(c_{rel,vtdj}) &~=~ (c_{rel,vtdj})^{ElasVKT_{cv}}-1 \\ 
M_{jsdt} &~=~ \left ( 1 + m_{vtdj}(c_{rel,vtdj}) \right ) \gamma_{USD} (1+\rho_{HailPool}) 
\end {align}
$$

And the proportional change in VMT for the combined scenario is

$$\Delta M_{jsdt} = 1 - M_{jsdt}$$

# 5. Policy and Scenario Calculations

Energy intensity changes (net, accounting for the influence of all identified mechanisms) 
have been calculated by year *t*, vehicle class *v*, and technology scenario scenario *j* in `EnergyIntensityChanges`:

$$\Delta I_{tkv} = 1 - \mu_{jtv}$$
Travel demand or VMT fractional changes have been calculated by year *t*, vehicle class *v*, and technology scenario scenario *j* in `VMTIncrease`

$$m_{vtdj}(c_{rel,vtdj}) ~=~ (c_{rel,vtdj})^{ElasVKT_{cv}}-1$$

# 6. Unifying Demand Framework

Rather than relying on an aggregate elasticity of travel demand with respect to generalized travel cost, we can derive demand as the result of consumer or household utility maximization. 

$$max_{M,T,C,X} ~U = u((M,T,C, \bar G), X) - \phi(P(\bar F, \bar M)) - \delta(A(\bar M))$$
Utility is a direct function of household travel distance (PKT) *M*, travel time *T*, generalized goods consumption *C*, and liesure *X*, as well as exogenous government goods $\bar G$. Consumer utility is also affected by damages from average pollution levels *P* and accident risk *A*. Those levels depend on average vehicle travel $\bar M$ and fuel use $\bar F$, which are also taken as exognous by the private decision maker. Average, or region-wide, travel $\bar M$ also affects congestion and thereby average travel speeds and time spent traveling.

*Note:* need to introduce (effective) occupancy *o* to relate PKT $M_V$ to VKT $M_V$, perhaps at the point of final demand. $M_P = o \cdot M_V$. Occupancy *o* can be taken as exognous initially, but extend to become an endogenous result of private preferences (over pooling space and time implications) and VKT/PKT production costs.

In the traditional travel demand literature specification (e.g. Small and Verhauf) the utility maximization is subject to dual budget constraints: the usual consumer/household financial budget constraint given income $I$, plus a constraint on total time $\underline L$ available to the consumer. The two constraints are connected since income *I* must be generated by time-consuming labor *L*.

$$\begin {align}
s.t.: ~& L+T+X ~\le~ \underline L \\
& (p_F + \tau_F) F + \tau_M M + H + C ~\le~ I \\
&I ~=~ L w (1-\tau_L)
\end {align}
$$
The assumed separability of leisure time $u(M,T,C, \bar G,X) = u(\psi(M,T,C, \bar G), X)$ has certain technical implications that simplify analysis.

Functions for the production of VKT from fuel use *F* and other monetary expenditures *H* on vehicles and travel link *F* and *H* to VKT *M*.

$$M = m(F,H)$$
Disaggregating VMT by vehicle class *v* (and accounting for different fuel efficiency and capital/operating costs by vehicle-class specific functions $m_v$)

$$M_v = m_v(F_v, H_v)$$
With total VKT and fuel use being the sums

$$M ~=~ \sum_v M_v$$
$$F ~=~ \sum_v F_v$$

Vehicle monetary costs $H_v$ per km include the cost categories: {Capital, Ins, Maint, ParkingAndFees, [internal accident and congestion costs]}; but exclude the cost of travel time.

### 7.1 Consumer Optimization

A representative agent (driver) that maximizes utility *U* of goods consumption, *C*, miles driven, *M*, time spent driving, *T*, and leisure, *N*, given government payments G, and suffering from pollution, *P*, and traffic accidents, *A*. 
The driver chooses which type of vehicle to drive a AV or MV, the number of miles driven *M*, fuel consumption *F*, expenditures on the vehicle (and other financial inputs of road travel) *H*, and  time driving *T*. The expected external accident cost is influenced by vehicle choice, AV or MV, but otherwise exogenous to the private choice, along with pollution damages *P*. One significant area that we do not yet model is a mixed fleet of CAVs and MVs. In this situation CAVs would likely reduce the average accident rate of MVs by their superior collision avoidance behavior.

$$U_{ij}=u(\psi(C_{i},M_{ij},T_{ij},G),N )- \phi(P_{ij})- \delta(A_{i})$$
Where

* $C_{i}$ 	quantity of a numeraire consumption good, per capita
* $M_{ij}$ 	vehicle-miles of travel
* $T_{ij}$	time spent driving
* $G$	 government spending
* $N$ 	leisure
* $P_{ij}$	quantity of (local and global) pollution
* $A_{i}$ 	severity-adjusted traffic accidents
* $L$	labor supply
* $I = (1-t_L) L$, after tax income
* $F_{i}$  fuel consumption
* $P_F$ 	consumer price of fuel broken out into retail before taxes plus fuel taxes $P_R + t_F$
* $H_{i}$   	Vehicle and Other driving costs 

Mileage (VMT) is produced from fuel and non-fuel (including vehicle) cost inputs, $M_{ij}= m(F_{ij},H_i)$, where $F_i$ is fuel consumption and $H_i$ is monetary measure of other driving costs that depend on vehicle prices and attributes. We note that average miles driven and fuel consumption is likely to differ in an urban and rural location. Driving time is determined by the VMT and average speed on the road network, $T_{ij} = \pi(\bar M ) M_{ij}$.
Here $\pi$ is the inverse of average travel speed ("pace," in hours per mile). Pace $\pi$ is a function of $\bar M$, the aggregate (average) miles driven per capita, where $\partial \pi/\partial \bar M >0$, more aggregate driving increases congestion and lowers the speed of driving. The pace of vehicles is expected to increase with greater CAV adoption due to platooning and traffic smoothing and accident avoidance (Wadud et al., 2016). Agents choose their own VMT *M* and as mentioned take the average level of driving by everyone $\bar M$ as fixed and hence pace $\pi$ and congestion as external and fixed. Private agents thus ignore the impact of their own behavior on congestion. 

### 7.2 Private Optimality Conditions 
Private behavior maximizes utility $U$, taking taxes, congestion, pollution, and accident risk as fixed. Environmental variables are fixed because they are functions of aggregate market behavior, i.e. average fuel-use and VMT $\bar F$ and $\bar M$, also taken as fixed from the private perspective. This maximization yields the private indirect utility $V$.[^2]


$$\begin{align}
V(.)~ \equiv
&Max ~~ L (C_{i},F_{i},\bar F_i,H_{i},\bar M_{ij},G,N,L,\mu,\lambda) \\
&= u \left ( \psi (C_{i},m(F_{i},H_{i} ),\pi (\bar M_i)m(F_{i},H_{i} ),G), N \right )  \\
&- \phi (P_F (\bar F_i) + P_M(\bar M_i)) - \delta(a(\bar M_i) \bar M_i)\\ 
&+ \mu \left \{ m(F_{ij},H_{ij}) - (\bar M_i) \right \} \\
&+ \lambda \left \{ (1-t_L)  \left ( \bar L - N - \pi(\bar M_i) m(F_{ij},H_{i}) \right ) - C_{ij} - (q_F  + q_T ) F_{ij} - H_{i} \right \}
\end{align}
\label{LagrangianFullSubscripts}$$

[^2]: The Lagrangian includes the constraints for VMT production, and time and financial budgets.

### 7.3 Social Optimality Conditions
The socially efficient fuel tax is determined by maximizing the private (representative consumer's) indirect utility $V$ with respect to fuel tax rate $t_F$. Setting this total derivative $dV/dt_F$ to zero yields the first-order necessary condition for the optimum:[^3]

[^3]: We have suppressed subscripts for readability, and without loss, since we evaluate efficient incentives separately for each vehicle type and region. 

$$\begin{align}
\frac{1}{\lambda} \frac{dV}{dt_F} & = (E^{P_F} - t_F) \left( - \frac{dF}{dt_F} \right ) + 
(E^C + E^A + E^{P_M}) \left ( - \frac{dM}{dt_F} \right ) + t_L \frac{dL}{dt_F}\\
& = 0 ~~\text{at social optimum}
\end{align}$$

where

* $\lambda$ is marginal utility of income
* $E^{P_F} = \phi' P_F'/\lambda$ is marginal pollution cost from fuels
* $E^{P_M} = \phi' P_M'/\lambda$ is marginal pollution cost from miles
* $E^C = \nu \pi' M, ~~ v \equiv 1-t_L- u_T/\lambda$ is marginal congestion cost
* $E^A = \delta' A'/\lambda$ is marginal accident costs

As noted earlier, for private decision making they are treated as a constant. For social planning we need to account for changes in total and average behavior, particularly changes in average VMT $\bar M$ and fuel use  $\bar F$, which alter $P$ and $A$.

The three terms in the efficient fuel tax first-order conditions correspond to the welfare changes from fuel use change, VMT change, and labor change respectively, each responding to the change in tax. This derivation presumes no taxation of vehicle miles travel *M*, i.e. $t_M = 0$. We relax that later.

### 7.4 Efficient Fuel Tax Incentive
By setting the marginal net benefit of fuel taxation to zero we can solve for the optimal or efficient fuel use incentive $t_F^*$. An objection than can be raised to this approach is that that are more distortions to the vehicle and fuel markets than we address. Therefore, we cannot have an "efficient" tax. We acknowledge this objection but note that our discussion of efficient taxation is consistent with a large body of literature that draws system boundaries that addresses the question of efficient or best taxation assuming rational agents and the regulatory and capital markets as they are at present. 

We note that the marginal benefit function applies to the private or household optimization over fuel use, vehicle fuel economy, and VMT when average travel and fuel use outcomes $\bar M$ and $\bar F$ are taken as fixed, generating external congestion, accident and pollution damage costs that are exogenous to the household. The same formalism yields the social optimum when the marginal net benefit with respect to fuel tax also accounts for how average (total) travel and fuel use vary with taxation. 

The Pigouvian portion of the efficient fuel tax,$MEC_F$, is based on the marginal external cost of fuel, including the direct external cost of fuel combustion $E^{P_F}$ (fuel-related pollution and energy security, plus marginal external congestion $E^C$, external accident $E^A$, and VMT-related pollution $E^{P_M}$ in units of dollars/gallon:
$$MEC_F(t_F) \equiv E^{P_F} + \left ( b_{M} / a_{FM}(t_F) \right ) \left( E^C + E^A + E^{P_M} \right)$$

The Adjusted Pigouvian tax $\tau_F^*$ adjusts the Pigouvian fuel tax for the inefficiency of the gas tax compared to labor tax (based on narrowness of the fuel tax base).
It is also supplemented by terms accounting for the *Ramsey tax* which is the portion of efficient fuel tax that accounts for the relative elasticity of demand for taxed activity and the *Congestion Feedback tax* portion of efficient fuel tax. 

Using the parameters discussed below, we solve for the efficient tax rate using the rootSolve non-linear solver in R-Studio (Soetaert and authors, 2016).

### 7.5 Data and Parameters

We parameterize the model focusing on how AVs are expected to *differ* from MVs including safety, fuel efficiency and travel time costs. Where AVs and MVs do not significantly differ we use inflation-adjusted parameters from Parry and Small (2005). We also update the model to account for changes in real fuel prices, taxes, costs (damages). Our data (described below) runs in 5 year time steps from 2015 - 2040. Base year (2015) values (all costs in 2016 dollars) for these parameters are shown in Table 1. Shown are cases that represent fleet Average MVs, New MVs, fleet average AVs, and new AVs. 

Table 1: Principal Parameters Used in Model

Variable                     Year   Units         P&S         Ave MV      New MV      Ave AV      New AV
--------------------------   -----  ---------     ---------   ---------   ---------   ---------   ---------
Fuel Economy          	     2015   mi/gal        20.00       21.71        24.51      32.60        36.80
                      	     2040                 NA          36.34        36.93      54.50        55.40
Fuel Damages GHG       	     2015   cents/gal     8.22        36.50        36.50      36.50        36.50
                      	     2040                 NA          60.80        60.80      60.80        60.80
Fuel Damages Energy Security 2015   cents/gal     0.00        19.00        19.00      19.00        19.00
                             2040                 NA          22.00        22.00      22.00        22.00
Congestion Costs	           2015   cents/mi      4.80        5.57         5.57       2.78         2.78
                	           2040                 NA          5.57         5.57       2.78         2.78
Accident Costs               2015   cents/mi      4.11        2.70         2.70       varies       varies
                             2040                 NA          2.70         2.70       varies       varies
Retail Price Gas no Tax	     2015   cents/gal     128.82      178.00       178.00     178.00       178.00
                       	     2040                 NA          178.00       178.00     178.00       178.00
Base Tax Rate Gasoline       2015   cents/gal     54.82       48.86        48.86      48.86        48.86     
                             2040                 NA          48.86        48.86      48.86        48.86     
--------------------------   -----  ---------     ---------   ---------   ---------   ---------   ----------

Notes:  All costs in $2016, Parry and Small (2005) estimates are for year 2000. 

### 7.6 Welfare Implications of Alternative Taxation Approaches

The per-capita welfare function used to determine efficient tax levels allows us to infer the welfare implications of an incremental tax change to alternative levels. As a linear approximation, and normalizing the welfare change as a fraction of initial fuel costs excluding tax, $q_f F_0$, provides a convenient relative welfare measure:
$$\frac {dw}{d t_F} =\frac {1}{q_f F_0} \frac {1}{\lambda} \frac {dV}{d t_F} = \frac {(1+MEB_L) }{q_f F_0} \left ( n_{FF} \frac {F}{q_F + t_F} \right ) (t_F^* - t_F)$$
where $F_0$ is the initial per capita fuel consumption and fuel price $q_F$ is taken as fixed. 
$$\frac {dw}{d t_F} = \frac {1}{q_f F_)} \frac {1}{\lambda} \frac {dV}{d t_F} = (1+MEB_L(t_F)) \frac {F(t_F)}{ F_0 q_f} n_{FF} \left ( \frac {t_F^* - t_F}{q_F + t_F} \right )$$
Given the treatment of F as iso-elastic in final (tax-inclusive) price, we can substitute for *F*
$$\begin {align}
\frac {dw}{d t_F} = \frac {1}{q_f F_)} \frac {1}{\lambda} \frac {dV}{d t_F} 
=&(1+MEB_L(t_F)) \frac {F_0}{ F_0 q_f} \left ( \frac {q_F+t_F}{ q_F+t_{F0}} \right )^{-n_{FF}} n_{FF} \left ( \frac {t_F^* - t_F}{q_F + t_F} \right ) \\
=&(1+MEB_L(t_F)) \frac {1}{q_f} \left ( \frac {q_F+t_F}{ q_F+t_{F0}} \right )^{-n_{FF}} n_{FF} \left ( \frac {t_F^* - t_F}{q_F + t_F} \right ) \\
\end {align}
$$
We integrate this numerically from current tax level $t_{F0}$ to alternative tax levels, taking initial fuel demand, fuel price ex-tax, and own-price elasticity of fuel demand as fixed - though they vary with the fuel tax level and fuel demand.

Note that this expression for marginal welfare change is zero at the efficient (welfare-maximizing) tax level, as expected.
$$\Delta w(t_1, t_2) = \int_{t_1}^{t_2}
\frac {dw}{d t_F} d t_F = 
\int_{t_1}^{t_2}(1+MEB_L(t_F)) \frac {1}{q_f} \left ( \frac {q_F+t_F}{ q_F+t_{F0}} \right )^{-n_{FF}} n_{FF} \left ( \frac {t_F^* - t_F}{q_F + t_F} \right ) d t_F
$$
[Note: this expression for welfare _cannot_ be used to directly to identify the socially optimal tax by welfare maximization, since $t_F^*$ is required for the marginal welfare expression, and all welfare changes are essentially measured relative to that efficient tax level.]

In this calculation we take the following terms as constant: initial fuel demand, fuel price, own-price elasticity of fuel demand
- $F_0$, $q_F$, $n_{FF}$
and these terms vary with fuel tax level $t_F$: fuel demand, 
- *F*, $MEB_L$

and integrate from the previously solved (efficient) tax level $t_F^*$ to any alternative level *t*.


# 8. Initial Integration of Approaches

# 9. Extensions for Initial Representation of Ride Hailing and Pooling

