---
title: "Notes on Private vs. Commercial Ownership of CAVs"
author: "Paul Leiby"
date: "11/8/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dimensions of the Issue

In full, this parameter assumption could be differentiated across many dimentions:

1. Shared (Commercial) vs. Private (Household) Ownership
2. Manual/Conventional Vehicle vs. "CAV"
3. Level of Automation for "CAV"
4. CAV Adoption (Fraction of Sales or stock that is CAV)
5. Near/Mid-term vs. Long-term
6. High vs. Low vs. Reference case

Here we restrict our attention to only dimensions 1, 2, and 6, implying the need for 2 x 2 x 3 or 12 parameters. Thus we start with three scenarios for 2 shares variables:

  - Fraction of CAVs which is private (household) vs. shared (commercial)
  - Fraction of Manual Vehicles which is private (household) vs. shared (commercial)

## Zeroth-Order Proposal (Pending interaction with A. Duvall and others)

**Fraction of CAVs which is private (household) vs. shared (commercial)**

Case        | Shared CAV Fraction| Private CAV Fraction| Notes
------------|----------------|-----------------|---------
Reference   | 100%           | 0%              | Per AEO2018, CAEVs are 1% of LDV sales by 2050
Low         | 16%            | 84%             | Per AEO2018, for CAEVs or CAHEVs 31% of LDV sales by 2050
High        | 90%            | 10%             | Virtual elimination of private vehs except for rich/rural

**Fraction of Manual Vehicles which is private (household) vs. shared (commercial)**

Case        | Shared MV Fraction| Private MV Fraction| Notes
------------|----------------|-----------------|---------
Reference   | 99%           | 1%               | Uber has 750k active drivers in US, Lyft 1400k
Low         | TBD%            | 100-TDB%             | XXX
High        | TBD%            | 100-TBD%             | XXX

## Considerations For Shared (commercial) vs. Private (Household) Ownership of CAVs

- Costs:
  - An argument for shared ownership is the high capital cost (and potentially low operating cost) of CAVs, especially CAEVs.
  - On other hand, private households seem willing to bear high fixed costs of vehicles
    - Boesch et al. 2018 conclude, after a review of costs: "Moreover, the results suggest that a substantial share of vehicles may remain in private possession and use due to their low variable costs. Even more than today, high fixed costs of private vehicles will continue to be accepted, given the various benefits of a private mobility robot.
  
- Timing/maturity: Many anticipate that the fraction of shared/commercial ownership will be higher initially, given 
  - the need to utilize the CAVs, to amortize their higher initial capital cost
  - uncertainty and technical challenges to user in early technology may deter private adoption
  - rapid technology change may may early CAVs obsolete quickly, deterring private adoption and suiting shared fleets who utilize and wear out (amortize) vehicles more quickly
  
- EV Needs
  - If Electrified EV, arguments on ownership cut both ways.


  
## Considerations For Shared (commercial) vs. Private (Household) Ownership of COnventional Vehicles

## Extant Estimates/Scenarios

1. In EIA/Chase et al. 2018, an "Issue in Focus from the Annual Energy Outlook 2018" on Autonomous vehicles:
  - Reference: The AEO 2018 Reference case seems a good starting point for a SMART Mobility Reference Case

  - Autonomous vehicles enter fleet light-duty vehicles
    - 1% of new light-duty passenger vehicles sales by 2050
    - 100% are fleet sales

  - "Scenarios assume that purchasing an autonomous vehicle is favorable for both households and fleet operators."
  - Assumptions: AEV (Autonomous Electric Vehicles) and AHEV Scenarios both assume:
    - 31% of new light-duty passenger vehicle sales by 2050
    - 16% of these are new fleet sales and 84% are new household sales by 2050

## References
* Patrick M.Bösch, Felix Becker, Henrik Becker, Kay W.Axhausen 2018. "Cost-based analysis of autonomous mobility services," _Transport Policy_ 64:76-91, May.

* Chase, Nicholas, 2018. "Autonomous Vehicles: Uncertainties and Energy
Implications" For 2018 EIA Energy Conference, June 5, 2018, Washington, DC
https://www.eia.gov/conference/2018/pdf/presentations/nicholas_chase.pdf

* Chase, Nicholas, John Maples, and Mark Shipper 2018. Autonomous Vehicles:
Uncertainties and Energy Implications, Issue in Focus from the Annual Energy Outlook 2018,
May 2018, U.S. Department of Energy, https://www.eia.gov/outlooks/aeo/pdf/AV.pdf

* Pofuk, Tin 2017. Autonomous Vehicles and the Future of Private Vehicle Ownership,
http://www.hippocampus.si/ISBN/978-961-7023-71-8/175.pdf
University of Primorska, Faculty of Management, Slovenia, tin.pofuk@fm-kp.si

* Patrícia S. Lavieri, Venu M. Garikapati, Chandra R. Bhat (corresponding author), 
Ram M. Pendyala, Sebastian Astroza, Felipe F. Dias, 2018. MODELING INDIVIDUAL PREFERENCES FOR OWNERSHIP AND SHARING OF AUTONOMOUS VEHICLE TECHNOLOGIES 
http://www.caee.utexas.edu/prof/bhat/ABSTRACTS/AV_paper.pdf

* UC Davis 2018. Paper Scenarios